services:
  web:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 80:80
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: "python manage.py runserver 0.0.0.0:8000"
