services:
  app:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 8081:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - appnet
    command: python manage.py runserver
  
networks:
  appnet:
    driver: bridge
